### ISSUE TITLE
potential fix for panel bubble location

### ISSUE THREAD

**Issue by robinplace** [Thoma5/gnome-shell-extension-bottompanel#6]
First off, nice extension.

I've figured out a workaround in my own system for your known issue with the panel bubble's location being several pixels too high.  Adding the following rule to my user theme's `gnome-shell.css` makes it just beautiful:

``` css
.popup-menu.panel-menu {
    margin-bottom: 0;
}
```

I don't know Gnome's JS APIs well, but I'd bet there's some simple way to load in this CSS, overriding the user theme's style.
